### ISSUE TITLE
Python 3.5 Support

### ISSUE THREAD

**Issue by peervm** [devcartel/pyrfa#19]
Hi, do you have any plans to add Python 3.5 support?

**Comment by ukrit-himakoon** [comment]
Hello Peer,

Could you please clarify the platform version that you run Python 3.5?

Thanks,
Ukrit H.

**Comment by peervm** [comment]
Currently I use PyRFA 7.6.0.2 on Py2.7 Win32 but need to upgrade, and would like jump straight to PyRFA 8.x on Py3.5 Win32.

But if that is not possible then Py3.5 Win64

Thanks.

**Comment by wiwat-tharateeraparb** [comment]
PyRFA 8 does not support 32bit platforms anymore. We are looking forward to support Python 3.5 with PyRFA 8 64bit (Win and Linux.) We will keep you updated on this.

If you are migrating from 7.6.0.2, note that since PyRFA 7.6.1.3, PyRFA's tuple output format from `dispatchEventQueue()` has been changed to be the same as PyRFA 8. See http://devcartel.com/blog/14169100.

**Comment by peervm** [comment]
Thanks.

And appreciate the link regarding the `dispatchEventQueue()`

**Comment by wiwat-tharateeraparb** [comment]
PyRFA 8.0.2 released today supports Python 3.5.

**Comment by peervm** [comment]
Awesome - thanks for the quick turnaround time.
